# Appium Server
appiumURL=http://127.0.0.1:4723

# Device Configuration
platformName=Android
deviceName=Android
automationName=UiAutomator2

# App Details
appPackage=com.sportstechbrands.sportstechlive
appActivity=com.sportstechbrands.sportstechlive.activities.newUiDesignRewamp.Welcome
appWaitActivity=com.sportstechbrands.sportstechlive.*

# App Behavior
noReset=true
ignoreHiddenApiPolicyError=true

# Test Data
email=protest@gmail.com
password=Test@123